fix configuration comparation

diff --git a/wava-core/src/main/scripts/wava-update b/wava-core/src/main/scripts/wava-update
--- a/wava-core/src/main/scripts/wava-update
+++ b/wava-core/src/main/scripts/wava-update
@@ -25,7 +25,7 @@ unzip -o /tmp/wava-latest-dist.zip -d /tmp &> /dev/null
 
 if [ -d $WAVA_HOME ]; then
     echo "Checking current configuration..."
-    cmp --silent $WAVA_HOME/cfg/wava.json.default /tmp/wava-$WAVA_VERSION/cfg/wava.json.default && cp -f $WAVA_HOME/cfg/wava.json /tmp/wava-$WAVA_VERSION/cfg/wava.json || echo "Configuration file structure has changed. A manual review of the configuration is required."
+    cmp --silent $WAVA_HOME/cfg/wava.json.default /tmp/wava-core-$WAVA_VERSION/cfg/wava.json.default && cp -f $WAVA_HOME/cfg/wava.json /tmp/wava-core-$WAVA_VERSION/cfg/wava.json || echo "Configuration file structure has changed. A manual review of the configuration is required. Old version can be found at $WAVA_HOME/wava-back"
 fi
 
 echo "Setting file permissions..."
